(function(g){var window=this;var UY=function(a){a.g||(a.g=new g.Vo,g.G(a,a.g));return a.g},VY=function(a){a.M("cardstatechange",a.sd()&&a.ue()?1:0)},WY=function(a){var b=g.Uh(a);
a=g.ai(a);return new g.vh(b.x,b.y,a.width,a.height)},XY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},YY=function(a){return"none"!=a.style.display},Fma=function(a){var b=g.Oh(a,"fontSize");
var c=(c=b.match(Cma))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.$d){if(String(c)in Dma)return g.ci(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Ema)return a=a.parentNode,c=g.Oh(a,"fontSize"),g.ci(a,b==c?"1em":b,"left","pixelLeft")}c=g.ee("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.ke(c);return b},Gma=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Vk&&a.dataset){if(g.yc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Kc("pollChoiceIndex"))},aZ=function(a){a=g.Ta(a);
delete ZY[a];g.lc(ZY)&&$Y&&$Y.stop()},bZ=function(){$Y||($Y=new g.L(function(){Hma()},20));
var a=$Y;a.isActive()||a.start()},Hma=function(){var a=(0,g.B)();
g.Zb(ZY,function(b){cZ(b,a)});
g.lc(ZY)||bZ()},dZ=function(a,b){g.Df.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},eZ=function(a,b,c,d){g.uo.call(this);
if(!g.Na(a)||!g.Na(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.B=d;this.coords=[];this.progress=this.D=0;this.A=null},cZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;fZ(a,a.progress);1==a.progress?(a.g=0,aZ(a),a.Xc(),a.l()):1==a.g&&a.rr()},fZ=function(a,b){g.Pa(a.B)&&(b=a.B(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},gZ=function(a,b,c,d,e){eZ.call(this,b,c,d,e);
this.element=a},hZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
gZ.call(this,a,b,c,d,e)},Ima=function(a){return Math.pow(a,3)},Jma=function(a){return 3*a*a-2*a*a*a},iZ=function(a){g.E.call(this);
this.i=a||window;this.g=[]},Kma=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.Yr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},jZ=function(a,b){(0,g.A)(b,function(b){g.Ls("visualElementShown",{csn:a,
ve:g.Us(b),eventType:4},g.Qs,void 0,void 0)})},kZ=function(a,b){(0,g.A)(b,function(b){g.Ls("visualElementHidden",{csn:a,
ve:g.Us(b),eventType:8},g.Qs,void 0,void 0)})},lZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Yc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={lD:a.impression,click:a.click,close:a.close,LL:a.teaser_impression,ts:a.teaser_click};b=b.tracking_params||{};this.A=g.Ts(b.card);this.D=g.Ts(b.teaser);this.u=g.Ts(b.icon)},mZ=function(a,b){g.bg.call(this);
this.zj=a;this.xp=b;this[g.Ff]=!1},rZ=function(a,b,c,d){mZ.call(this,a,b);
a=this.xp;b=this.ha();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.t(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Lma(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.xp;a=this.ha();if(d instanceof nZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof oZ){b="lg-"+d.u+"-"+d.B+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=pZ(c,"linearGradient",{x1:d.u,y1:d.B,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ia(d.l)&&(f+=";stop-opacity:"+d.l);f=pZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ia(d.o)&&(f+=";stop-opacity:"+d.o);d=pZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=qZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},sZ=function(){},tZ=function(a,b){mZ.call(this,a,b)},uZ=function(){this.Ta=[];
this.Ba=[];this.Md=[]},vZ=function(a,b,c,d){var e=a.ud[0]-b*Math.cos(g.Gd(d))+b*Math.cos(g.Gd(d+90)),f=a.ud[1]-c*Math.sin(g.Gd(d))+c*Math.sin(g.Gd(d+90));
a.Ta.push(3);a.Ba.push(1);a.Md.push(b,c,d,90,e,f);a.zk=!1;a.ud=[e,f]},Nma=function(a,b){for(var c=a.Md,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Mma[k]*a.Ba[e];
b(k,c.slice(d,d+l));d+=l}},wZ=function(a,b,c,d){rZ.call(this,a,b,c,d)},xZ=function(a,b){this.g=a;
this.i=b},yZ=function(a,b,c,d,e){g.Fo.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Lma=function(a){var b=a.pj();
return b?b.width/(a.l?new g.Jd(a.l,a.I):a.pj()).width:0},oZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.B=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ga(k)?k:null;this.o=g.Ga(l)?l:null},nZ=function(a,b){this.F=a;
this.H=null==b?1:b},zZ=function(a,b){mZ.call(this,a,b)},AZ=function(a,b,c,d){rZ.call(this,a,b,c,d)},BZ=function(a,b,c,d,e){yZ.call(this,a,b,c,d,e);
this.g={};this.O=g.be&&!g.Sc(526);this.P=new g.yn(this)},pZ=function(a,b,c){a=a.N.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},CZ=function(a,b,c,d){b=pZ(a,"path",{d:Oma(b)});
c=new AZ(b,a,c,d);a.o.ha().appendChild(c.ha())},Oma=function(a){var b=[];
Nma(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},qZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Pma++;c.setAttribute("id",d);a.g[b]=d;a.B.appendChild(c);return d},Qma=function(){DZ||(DZ=new g.Og(400),DZ.start());
return DZ},EZ=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.D)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.D)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.Ts(a.trackingParams);var k=(0,g.D)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.Mu=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.D)(x.loggingUrls||[],c);l.Xk=g.gc(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.D)(k.impressionUrls||[],c);l.jD=(0,g.D)(k.hovercardShowUrls||[],c);l.Yc={itct:k.trackingParams};l.visualElement=g.Ts(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.Ul=!1,l.In=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.Ul=!1,l.In=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.gc(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Ul=!1;l.In="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var C=d(m.subscribedButtonText);if(m.subscribed){var F=d(m.subscriberCountWithUnsubscribeText);var H=d(m.subscriberCountText)}else F=d(m.subscriberCountText),H=d(m.subscriberCountWithSubscribeText);
var T=null;if(k.signinEndpoint&&(T=g.gc(k,"signinEndpoint","webNavigationEndpointData","url"),!T)){k=void 0;break a}if(x&&(C||T)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:F,unsubscribeText:C,unsubscribeCount:H,enabled:m.enabled,signinUrl:T,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.gc(x,"urlEndpoint","url"),l.Ul=!0,l.In="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.le)(k,function(a){return!!a});
return f},FZ=function(a){g.eK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.B={};this.A=this.l=null;this.I=[];a=g.V(a);this.P=g.Ky(a)||g.Ly(a);this.Xz=!0;this.D=0;this.F=new g.ko;this.u=new g.bs(this);g.G(this,this.u);this.u.K(this.player,g.DD("creatorendscreen"),this.hE);this.u.K(this.player,"crx_creatorendscreen",this.iE);this.u.K(this.player,"resize",this.qb);this.u.K(window,"focus",this.SK);this.load();var b=g.fe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Af(this,function(){g.ke(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},GZ=function(a){return a.player.getVideoData().Xb?"current":a.P?"new":"current"},HZ=function(a){return"creator-endscreen-editor"===a},IZ=function(a,b){g.OJ(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.I.length&&(a.I.forEach(function(a){a.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Rma(a);c=[];var d=new g.AD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.V(a.player).g||(a.l=new g.S({C:"div",G:"ytp-ce-shadow"}),g.SJ(a.player,a.l.element,4),a.A=new g.tP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Sma(a,e);a.g[e.id]=f;a.B[e.id]=e;g.SJ(a.player,f.element,4);var k=new g.AD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Tma(a,f,e)}g.LJ(a.player,
c);a.qb()}},Rma=function(a){var b=g.kt(),c=g.lt();
c&&b&&g.Vs(c,b,[a.i.visualElement])},Sma=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={C:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Xk||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:JZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.lo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.S(c);break;case "PLAYLIST":c={C:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Xk||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:JZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.lo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-playlist-count",J:[{C:"div",
G:"ytp-ce-playlist-icon"},{C:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.S(c);break;case "CHANNEL":c={C:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Xk||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",
J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{C:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.lo(a.F,b.title||"")},U:b.title},b.subscribeButton?{C:"div",G:"ytp-ce-subscribe-container",J:[{C:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{C:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{C:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:JZ(b)}]};c=new g.S(c);var d=g.Rd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.V(a.player).g){var e=null;var f=b.Yc.itct}else e="endscreen",f=null;e=new g.jV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={C:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Xk||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",
J:[{C:"div",G:"ytp-ce-website-title",L:{dir:g.lo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-website-metadata",U:b.metadata},{C:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:JZ(b)},{C:"div",G:"ytp-ce-expanding-icon",L:KZ(b.iconUrl)}]},c=new g.S(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},JZ=function(a){if(a.Mu)var b=a.Mu.thumbnails;
return KZ(b?b[b.length-1].url:null)},KZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},Tma=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.y)(a.Dq,a,b,c));b.ca("mouseleave",(0,g.y)(a.yr,a,b,c));g.V(a.player).g||b.ca("click",(0,g.y)(function(a){g.J(a.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.y)(a.hy,a,c));b.ca("keypress",(0,g.y)(a.hy,a,c));b.ca("focus",(0,g.y)(function(a,b){this.Dq(a,b)},a,b,c));
b.ca("blur",(0,g.y)(function(a,b){this.yr(a,b)},a,b,c));
b.ca("touchstart",(0,g.y)(a.Dq,a,b,c));var f=g.Td("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(a){a=a||window.event;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();g.ro(b.element,"ytp-ce-element-hover");g.ro(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.y)(function(a,b){this.Xz=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.y)(function(a,b,c){this.D+=c;0<this.D?(g.J(a.element,"ytp-ce-force-expand"),LZ(this,b.id,!0)):(g.ro(a.element,"ytp-ce-force-expand"),g.ro(a.element,"ytp-ce-element-hover"),LZ(this,b.id,!1))},a,b,c);
a=(0,g.y)(function(a,b){b&&(a.ca("blur",function(){YY(b)&&this.Xz&&b.focus()}),a.K(b,"focus",d),a.K(b,"blur",e))},a,b);
a(g.Td("ytp-sb-subscribe",b.element));a(g.Td("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},LZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},MZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||HZ(g.V(a.player).playerStyle))c&&c();else{b=Uma(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.lr(b[a],d)}},NZ=function(a,b,c){MZ(a,b.clickUrls,c);
(a=g.lt())&&b.Ul&&g.Xs(a,b.visualElement)},Uma=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Vma(b[e],c));return d},Vma=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},OZ=function(a){return g.Na(a)&&a.length?a[0]:a},PZ=function(a){var b=/.+/;
return g.t(a)&&null!=b&&null!=a&&a.match(b)?a:""},QZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},RZ=function(a){return g.t(a)?a:""},SZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},TZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},UZ=function(a,b){return g.t(a)?parseFloat(a):b},VZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Cd(a,b,c);if(a>=b&&a<=c)return a}return e},Wma=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},WZ=function(a,b){if(null==a)return null;
if(g.Oa(a)){var c=[];(0,g.A)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},Xma=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.sh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},Yma=function(a){function b(a){return(0,g.le)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},Zma=function(a){this.externalId=a},$ma=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},XZ=function(a){if(!a)return null;
var b=g.kd(RZ(a.value));b=g.hd(b);if(!b)return null;var c=SZ(a.target,ana,"current");return null==c?null:new $ma(b,c,TZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},YZ=function(a){return a.value?a.value:null},bna=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},ena=function(a){if(!a)return null;
var b=SZ(a.type,cna),c=SZ(a.trigger,dna),d=OZ(a.url);d=XZ(d?d:null);a=OZ(a.subscribeData);var e=a?a:null;e?(a=RZ(e.external_user_id),e=RZ(e.subscription_token),a=a&&e?new Zma(a):null):a=null;return b?new bna(b,c,d,a):null},ZZ=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},$Z=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},a_=function(a,b,c,d,e,f,k,l,m,n,q){this.x=a;
this.y=b;this.Fi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.B=l;this.o=m;this.i=n;this.g=q},b_=function(a,b){if(!a)return null;
var c=UZ(a.x,0),d=UZ(a.y,0),e=UZ(a.w,0),f=UZ(a.h,0),k=Wma(a.t),l=UZ(a.d,0),m=UZ(a.px,0),n=UZ(a.py,0),q=UZ(a.scaleSlope,1),u=UZ(a.scaleSlopeX,q);q=UZ(a.scaleSlopeY,q);var x=SZ(a.scaleDimension,fna,"xy");return b(c,d,e,f,k,l,m,n,u,q,x)},e_=function(a,b){var c=c_(b,d_(a,new g.vh(a.x,a.y,a.Fi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Cd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Cd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},d_=function(a,b,c){var d=a.A,e=a.B,f=a.g?a.g:"xy",k=ZZ(c,a.o,f);
a=$Z(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.vh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},f_=function(a){return a?b_(a,function(a,c,d,e,f,k,l,m,n,q,u){return new a_(a,c,d,e,f,k,l,m,n,q,u)}):null},g_=function(a,b){this.g=a;
this.i=b||null},c_=function(a,b){var c=a.i?e_(a.i,new g_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Hd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ia(c)&&(d.top+=c));return d},h_=function(a,b,c,d,e,f,k,l,m,n,q,u,x){a_.call(this,a,b,c,d,e,l,m,n,q,u,x);
this.D=f;this.F=k},gna=function(a){if(!a)return null;
var b=UZ(a.sx,0),c=UZ(a.sy,0);return b_(a,function(a,e,f,k,l,m,n,q,u,x,C){return new h_(a,e,f,k,l,b,c,m,n,q,u,x,C)})},hna=function(a,b,c,d,e,f,k,l,m,n,q,u,x,C){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=q;this.effects=u;this.cornerRadius=x;this.u=C},i_=function(a){if(!a)return null;
var b=QZ(a.fgColor,"#1A1A1A"),c=QZ(a.bgColor,"#FFF"),d=QZ(a.borderColor,"#000"),e=VZ(a.borderWidth,0,5,!1,0),f=VZ(a.bgAlpha,0,1,!1,.8),k=QZ(a.highlightFontColor,"#F2F2F2"),l=VZ(a.highlightWidth,0,5,!1,3),m=RZ(a.textAlign),n=VZ(a.textSize,3.3,30.1,!0,3.6107),q=RZ(a.fontWeight),u=Xma(a.padding),x=Yma(a.effects),C=VZ(a.cornerRadius,0,10,!0,0);a=OZ(a.gradient);if(a=a?a:null){var F=VZ(a.x1,0,100,!0,0),H=VZ(a.y1,0,100,!0,0),T=VZ(a.x2,0,100,!0,100),X=VZ(a.y2,0,100,!0,100),ra=QZ(a.color1,"#FFF"),wb=QZ(a.color2,
"#000");a=new ina(F,H,T,X,ra,wb,VZ(a.opacity1,0,100,!0,100),VZ(a.opacity2,0,100,!0,0))}else a=null;return new hna(b,c,d,e,f,k,l,m,n,q,u,x,C,a)},ina=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.B=k;this.D=l},jna=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},lna=function(a){if(!a)return null;
var b=SZ(a.type,kna,"rect"),c=WZ(a.rectRegion,f_),d=WZ(a.anchoredRegion,gna);a=WZ(a.shapelessRegion,f_);return new jna(b,c,d,a)},j_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},mna=function(a,b){this.i=a;
this.g=b},nna=function(a,b){this.state=a;
this.ref=b},k_=function(a){if(!a)return null;
var b=SZ(a.state,ona);a=PZ(a.ref);return b?new nna(b,a):null},pna=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},qna=function(a){if(!a)return null;
var b=WZ(a.condition,k_),c=WZ(a.notCondition,k_),d=TZ(a.show_delay,!1);a=TZ(a.hide_delay,!1);return b||c?new pna(b,c,d,a):null},rna=function(a,b,c){(0,g.A)(a.g,g.Wa(b,!1),c);
(0,g.A)(a.l,g.Wa(b,!0),c)},l_=function(a,b,c,d,e,f,k,l,m,n,q,u,x,C){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.B=l||[];this.i=m;this.A=n;this.u=q;this.data=u;this.g=x;this.itct=C},una=function(a){if(!a)return null;
var b=PZ(a.id),c=PZ(a.author),d=SZ(a.type,sna),e=SZ(a.style,m_),f=RZ(OZ(a.TEXT)),k=RZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=OZ(a.segment);var m=l?l:null;m?(PZ(m.timeRelative),l=PZ(m.spaceRelative),l=(m=WZ(m.movingRegion,lna))?new mna(l,m):null):l=null;m=WZ(a.action,ena);var n=WZ(a.trigger,qna),q=OZ(a.appearance);(q=i_(q?q:null))||(q=i_({}));var u=SZ(a.coordinate_system,tna,"video_relative"),x=TZ(a.closeable,!0),C=RZ(a.log_data);a=RZ(a.itct);return b&&d?new l_(b,c,d,e,f,l,m,n,q,u,x,k,C,a):null},
o_=function(a){return n_(a,function(a){return"click"==a.trigger})},n_=function(a,b){return(0,g.ck)(a.l,b,void 0)},vna=function(a,b,c){(0,g.A)(a.l,b,c)},wna=function(a,b){return g.eb(a.l,b,void 0)},p_=function(a,b,c){(0,g.A)(a.B,b,c)},xna=function(a,b){(0,g.D)(a.B,b,void 0)},r_=function(a){return(a=q_(a))?j_(a):null},q_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},s_=function(a,b){var c=r_(a);
return c&&b?$Z(b,c.i,c.g?c.g:"xy"):1},u_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;rna(b,function(a,b){var c=t_(b.state,b.ref);this.i.subscribe(c,(0,g.y)(this.o,this,c,a));this.g[c]=a},this)},t_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},v_=function(){this.g=!1;
this.u=this.i=null},w_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new BZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Cp(),a.u=g.ee("DIV"),a.u.appendChild(a.i.ha()));
return a.i},x_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Zb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},y_=function(a,b){var c=g.Eo(g.Do.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},yna=function(a,b){var c=y_(a,x_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=y_(a,x_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},x_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=y_(a,x_("feComposite",{"in":c,in2:b,operator:"in"}));return y_(a,x_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},zna=function(a,b){var c=y_(a,x_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=y_(a,x_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=y_(a,x_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=y_(a,x_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=y_(a,x_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=y_(a,x_("feComposite",{operator:"out","in":c,in2:d}));return y_(a,x_("feComposite",{operator:"over","in":b,in2:c}))},Ana=function(a,b){return b},Bna=function(a){var b=
x_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(a){a:{switch(a){case "bevel":a=yna;break a;case "dropshadow":a=zna;break a}a=Ana}c=a(b,c)});
return b},Cna=function(a){a=(0,g.le)(a,function(a){return a in z_});
g.Bb(a,function(a,c){return z_[a]-z_[c]});
return a},Dna=function(a){return g.eb(a,function(a){return"dropshadow"==a})?new g.sh(0,7,7,0):new g.sh(0,0,0,0)},A_=function(a,b,c){var d=new uZ;
d.moveTo(a.left+b+c,a.top+c);d.Wb(a.left+a.width-b-c,a.top+c);vZ(d,b,b,-90);d.Wb(a.left+a.width-c,a.top+a.height-b-c);vZ(d,b,b,0);d.Wb(a.left+b+c,a.top+a.height-c);vZ(d,b,b,90);d.Wb(a.left+c,a.top+b+c);vZ(d,b,b,180);d.close();return d},B_=function(a,b,c,d){var e=a.u;
e?a=new oZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.B,e.D):(b=a.g,a=new nZ(a.bgColor,d?Math.max(b,.9):b));return a},C_=function(a,b){var c=g.wh(a),d=Dna(b);
g.Qa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.vh(c.left,c.top,c.right-c.left,c.bottom-c.top)},D_=function(a,b,c){if(c.length&&(b=g.Rd(document,"g",void 0,b),b.length)){var d=Cna(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Bna(d),a=0<d.childNodes.length?qZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},E_=function(){v_.call(this);
this.o=0},Ena=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},F_=function(a){v_.apply(this,arguments)},G_=function(a){v_.apply(this,arguments)},H_=function(a){E_.apply(this,arguments)},I_=function(a,b,c,d,e){g.E.call(this);
this.g=a;this.V=b;this.A=c;this.X=d;this.Y=e;this.F=!1;this.ba=new iZ(this);g.G(this,this.ba);this.N=this.u=this.B=this.P=this.i=null;this.T=!1;this.aa=this.H=this.I=null;this.Nm=new g.Pl(this.LC,100,this);g.G(this,this.Nm);this.D=new g.L(this.Wv,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Fna=function(a,b){var c=(0,g.y)(function(a,c,f){c=f?J_(this,c,(0,g.y)(f,this)):J_(this,c);
this.ba.ca(b,a,c)},a);
c("mouseover","G",a.Tw);c("mouseout","F",a.kg);c("click","D");c("touchend","D")},Gna=function(a){if(a.g.u){if(n_(a.g,function(a){return"close"==a.type}))var b=a.i;
else a.o=g.ee("DIV","annotation-close-button"),g.bi(a.o,!1),g.Yp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(a){a.stopPropagation()};
a.ba.ca(b,"click",J_(a,"E",c));a.ba.ca(b,"touchend",J_(a,"E",c))}},J_=function(a,b,c){return(0,g.y)(function(a){if(this.Y)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.bi(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.ue(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.bi(d,
!0)}}d=WY(a.target);a=new g.Hd(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.X.M(b,this.g)},a)},M_=function(a){if(a.i||a.l){var b=r_(a.g);
if(b){var c=K_(a);if(a.i){b=e_(b,c);var d=g.CJ(a.A).getVideoContentRect();g.$h(a.i,b.width,b.height);g.Qh(a.i,b.left,b.top);a.P=new g.vh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=r_(a.g))&&d?ZZ(d,e.o,e.g?e.g:"xy"):1;var f=s_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.sh(d,d,d,d));d=new g.sh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.B&&(a.B.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.CJ(a.A).getVideoContentRect();var q=g.JJ(a.A);g.xh(n,q)?n=null:(q.top+=20,q.height-=40,"player_relative"!=a.g.A&&(q.left-=n.left,q.top-=n.top),n=q);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=L_(a,23,b,d,e);if(a.o){var u=43-f.width;0<u&&(b.left+f.left-u>n.left&&(f.left-=u),f.width+=u)}u=f;g.$h(a.u,f.width,f.height);g.Qh(a.u,f.left,f.top)}a.o&&(u?b=new g.Hd(u.left+
u.width-23-18,a.T?u.top+2:u.top+u.height-18-2):(u=L_(a,18,b,d,e),b=new g.Hd(u.left,u.top),g.$h(a.o,u.width,u.height)),g.Qh(a.o,b));a.N=new g.vh(a.P.left+u.left,a.P.top+u.top,u.width,u.height);a.I=a.ba.ca(g.CJ(a.A),"mousemove",a.VE,a)}else a.u&&(u=e/f*d.height*4.2/100,u=new g.Jd(u,u),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,u=new g.vh(b.width-u.width-e,b.height-u.height-e,u.width,u.height)):u=new g.vh(b.width-u.width-3*d.height/100,(b.height-u.height)/2,u.width,u.height),g.$h(a.u,
u.width,u.height),g.Qh(a.u,u.left,u.top)),a.o&&(u=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Qh(a.o,u&&e?new g.Hd(b.width-9,-9):u?new g.Hd(b.width-9,45<b.height?9:b.height-9):e?new g.Hd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Hd(45<b.width?b.width-9-18:-9,b.height-9):new g.Hd(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;u=g.CJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
s_(a.g,u)/100+"px";u=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==u||"highlightText"==u?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;u=(b=g.Td("annotation-link-icon",a))?YY(b):!1;e=(d=g.Td("annotation-close-button",a))?YY(d):!1;u&&g.bi(b,!1);e&&g.bi(d,!1);m=f="";if(n=g.Td("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Fma(a);q=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(q=l,l=Math.min(l+x,k)):l=Math.max(l-x,q),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=q&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=q+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.bi(d,!0);u&&g.bi(b,!0)}}}},L_=function(a,b,c,d,e){var f=0<e;
b=new g.vh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.T=!0);return b},N_=function(a){return"label"!=a.g.style||a.l.g},K_=function(a){var b=g.CJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.CJ(a.A).getPlayerSize();b=new g.vh(-b.left,-b.top,c.width,c.height)}else b=new g.vh(0,0,b.width,b.height);return new g_(b,a.O?r_(a.O):null)},O_=function(a,b){return b?new g.vh(a.x+b.left,a.y+b.top,b.width,b.height):null},P_=function(a,b,c){g.E.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Hna(b,a)},Hna=function(a,b){xna(a,function(c){return new u_(a.id,c,b)})},Q_=function(a){a.i.unsubscribe("resize",a.Sw,a);
a.i.unsubscribe("onVideoAreaChange",a.Jy,a)},R_=function(a){a.g&&(a.g.stop(),a.g=null)},S_=function(a,b,c){lZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},T_=function(a,b,c){lZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=XZ({target:"current",value:a});this.I=b.signin_title||null;this.H=b.signin_message||null},U_=function(a,b,c){T_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.B=b.innertube_request_params},V_=function(a,b,c){lZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},W_=function(a,b,c){lZ.call(this,a,b,c);
this.B=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=XZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},X_=function(a,b,c){T_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new Ina(a[b]))},Ina=function(a){this.merchant=g.Fc(a.merchant);
this.price=g.Fc(a.price)},Y_=function(a,b,c){T_.call(this,a,b,c);
this.P=b.ypc_item_type;this.F=b.ypc_item_id;this.B=b.ypc_flow_type},Z_=function(a,b,c){lZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},$_=function(a,b,c){lZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.B=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=XZ({target:b.target||"new",value:b.url})},Jna=function(a){this.g=a;
this.i={}},Kna=function(a){var b={};
b=(b["iv-event"]=1,b);g.IJ(a.g,"iv",b,void 0)},d0=function(a,b,c,d){if(b){var e=a0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=b0(a,"cta_annotation_shown",e,c);c0(a,e,Lna(b,d))}},e0=function(a,b,c,d,e,f){if(b){var k=a0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.tc(k,d);b=b0(a,"cta_annotation_clicked",k,e);c0(a,k,b,c,f)}},f0=function(a,b){if(b){var c=a0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=b0(a,"cta_annotation_closed",c);c0(a,c,d)}},Lna=function(a,b){return b?(0,g.D)(a,g.Wa(function(a,b){return g.Bn(b,a)},b)):a},b0=function(a,b,c,d){d=d?g.rb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.P(g.V(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.Wt){if((b=a.Wt[b])&&g.fv(b)){a=g.zc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.dn){b=g.Bq(a.dn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},c0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(a){f++;
g.lr(a,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.IJ(a.g,"iv",b,m)},a0=function(a,b){var c={};
if(b){var d=new g.pn(b);(0,g.A)(d.Ed(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.V(a.g).playerStyle;return c},g0=function(a,b,c,d,e){e=a0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;c0(a,e,d)},h0=function(a,b,c,d){c&&(c=a0(a,c),c["iv-event"]=b,c0(a,c,d))},Mna=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.sb=c;this.videoData=d;this.logger=e;this.ea=f;this.i=k},i0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.ko},Nna=function(a,b){var c=[];
(0,g.A)(b.choices,function(a){c.push({C:"li",G:b.B+"-"+a.index.toString(),J:[{C:"label",J:[{C:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.B+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{C:"span",G:"iv-card-poll-choice-text",J:[{C:"span",G:"iv-card-poll-choice-percent"},j0(this,"span",void 0,a.desc)]}]},{C:"div",G:"iv-card-poll-result",J:[{C:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={C:"ul",L:{role:"radiogroup"},J:c},e={};b.o&&(e["aria-label"]=g.AN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{C:"div",G:"iv-card-content",J:[j0(a,"h2",e,b.title),{C:"form",J:[{C:"fieldset",J:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({C:"div",W:["iv-card-sign-in"],J:[{C:"h2",U:"Want to vote?"},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:YZ(b.o)},J:[{C:"span",W:["iv-button-content"],U:"Sign in"}]}]}));f=new g.S({C:"div",
W:f,J:d});d=f.element;k0(b,d);Kma(a.g.g,d,g.Wa(a.B,b),a);(0,g.A)(g.Sd("iv-card-poll-choice-input",d),function(a){this.g.g.ca(a,"focus",g.Wa(this.l,!0));this.g.g.ca(a,"blur",g.Wa(this.l,!1))},a);
b.o&&(d=g.Td("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Yc,b.l,b.i.click,5));return f},o0=function(a,b,c,d){var e=b.displayDomain?{C:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=l0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{C:"a",G:"iv-click-target",L:{href:YZ(b.url)},J:[m0(b.imageUrl,e),{C:"div",G:"iv-card-content",J:[j0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({C:"div",W:["iv-card-sign-in"],J:[j0(a,"h2",void 0,b.I||""),{C:"p",U:b.H},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:YZ(b.g)},J:[j0(a,"span","iv-button-content","Sign in")]}]});k=new g.S({C:"div",W:k,J:e});n0(a,k,b,c,d);return k},q0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.B&&b.o?{C:"span",W:d,L:e,U:b.o}:"";c={C:"div",W:["iv-card",c],J:[{C:"a",G:"iv-click-target",L:{href:YZ(b.url)},J:[m0(b.F,d?{C:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{C:"div",G:"iv-card-content",J:[{C:"h2",G:"iv-card-primary-link",U:b.title},p0(a,b)]}]}]};c=new g.S(c);n0(a,c,b);return c},r0=function(a,b){return b.customMessage?j0(a,"div","iv-card-message",
b.customMessage):""},m0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{C:"div",G:"iv-card-image",L:{style:c},J:d}},p0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(a){c.push(j0(this,"li","",a))},a);
return{C:"ul",G:"iv-card-meta-info",J:c}},j0=function(a,b,c,d){c?g.t(c)?c={"class":c}:g.Na(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.lo(a.i,d);return{C:b,L:c,U:d}},l0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.lo(a.i,b.customMessage);var e=[{C:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({C:"span",G:"iv-card-link-icon"}));return{C:"div",W:c,L:d,J:e}},k0=function(a,b){var c=0;
(0,g.A)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Td(a.B+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Td("iv-card-poll-choice-percent",f);g.pe(l,g.AN("$PERCENT%",{PERCENT:k}));f=g.Td("iv-card-poll-result-bar",f);g.Ih(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.g);g.K(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},s0=function(a,b,c,d){d?(c&&a.g.videoData.sa||a.g.ea.pauseVideo(),a.g.ea.isFullscreen()&&a.g.ea.toggleFullscreen(),e0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.lt())&&g.Xs(a,b.A)):b.url&&a.u(b.url,b.id,b.Yc,b.l,b.i.click||[],5)},n0=function(a,b,c,d,e){c.g&&t0(a,g.Sd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&t0(a,g.Sd("iv-click-target",b.element),c,c.url,d)},t0=function(a,b,c,d,e){(0,g.A)(b,function(a){if(e){var b=(0,g.y)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.g.g.ca(a,"click",b)}else d&&this.o(a,d,c.id,c.Yc,c.l,c.i.click,5)},a)},u0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},w0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=v0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},v0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Ona=function(a){a=YZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!w0(a))||(b=g.$g(g.Zg(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.zq(a);if(!b||!b.v)return null;if(b=b.t)return u0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.xq(a[1]))&&a.t?u0(a.t):-1},x0=function(a){a=YZ(a);
a=a.replace(/https?:\/\//g,"");return w0(a)?(a=g.zq(a))&&a.v?a.v:null:null},Pna=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},y0=function(a,b){return b?b:w0(a)?"current":"new"},z0=function(a,b){g.E.call(this);
this.za=a;this.context=b;this.Ls=!1;this.X=0},Qna=function(a){return(0,g.B)()-a.X},Rna=function(a,b,c,d,e,f){var k=YZ(b);
if(k){var l=y0(k,b.target),m=(0,g.y)(function(){b.g&&this.context.ea.pauseVideo();var a=this.context.videoData.Xb||!1,d=g.zq(k||"");a&&d&&(d.v||d.list)?g.tX(this.context.ea.app,d.v,c,d.list,!1,void 0,void 0):g.SL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Qna(a);e0(a.context.logger,d,m,n,e,f);w0(k)||(a=g.lt(),d=c.itct,a&&d&&g.Xs(a,g.Ts(d)))}},C0=function(a,b,c){z0.call(this,b,c);
var d=this;this.i=a;this.V=null;this.T=this.wa=this.u=this.oa=!1;this.aa=null;this.N=new g.L(g.Ka,c.sb.Ic?4E3:3E3);g.G(this,this.N);this.ka=new g.L(g.Ka);g.G(this,this.ka);this.A=new i0(c,(0,g.y)(this.si,this),(0,g.y)(this.jm,this));this.F=new g.S({C:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{C:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{C:"span",G:"iv-drawer-header-text"},{C:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{C:"div",G:"iv-drawer-content"}]});
g.G(this,this.F);this.B=this.F.element;this.va=new g.tP(this.F,330);g.G(this,this.va);this.xa=g.Td("iv-drawer-header-text",this.B);this.o=g.Td("iv-drawer-content",this.B);this.l=[];this.ma=this.O=this.D=this.Y=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&A0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&B0(d)});
this.P=this.H=this.Z=null},Vna=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&D0[c]){c=new D0[c](b.id,b.data,b.g);if(!a.oa){g.qo(a.ha(),["html5-stop-propagation","iv-drawer-manager"]);g.SJ(a.i,a.B,5);Sna(a);a.O=g.Td("ytp-cards-button",a.i.getRootNode());var d=g.Td("iv-drawer-close-button",a.B);a.ma=d;a.oa=!0}E0(a,c.id);var e=Tna(a,c);if(e){d={Db:c,Io:e.element,tw:!1};var f=Una(a,d);g.ub(a.l,f,0,d);e.g(a.o,f);a.il();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Wa(a.AL,d)):(e=1E3*a.context.ea.getCurrentTime(),5E3>e&&e>c.startMs&&a.Dz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Wa(a.Dz,d)),F0(a))}}},Wna=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){A0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){B0(a)});
var c=b.data.headerText;g.pe(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.V=b.data.eventId);a.Z=g.Ts(b.data.trackingParams);a.P=g.Ts(b.data.closeTrackingParams);a.H=g.Ts(b.data.iconTrackingParams)},E0=function(a,b){var c=Xna(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Db.id),g.ke(c.Io),g.nb(a.l,c),a.il(),F0(a))},A0=function(a,b,c,d){if(!a.u){a.va.show();
a.Y=new g.L(function(){g.J(a.context.ea.getRootNode(),"ytp-iv-drawer-open")},0);
a.Y.start();a.aa=g.Pr(a.o,"mousewheel",(0,g.y)(a.xE,a));a.u=!0;a.X=(0,g.B)();g0(a.context.logger,a.V,7,void 0,d&&d.Db?d.Db.l:void 0);var e=g.lt();e&&a.Z&&a.P&&jZ(e,[a.Z,a.P]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(b){b.tw||(b.tw=!0,d0(a.context.logger,b.Db.l,b.Db.i.lD,f));e&&jZ(e,[b.Db.A])});
VY(a.i);c&&(a.D=new g.L(function(){a.fa=a.O;a.ma.focus()},330),a.D.start())}},B0=function(a){a.u&&(a.va.hide(),g.Qr(a.aa),a.aa=null,g.ro(a.context.ea.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,VY(a.i),a.D&&a.D.stop(),a.D=new g.L(function(){a.fa&&(a.fa.focus(),a.fa=null)},330),a.D.start())},Sna=function(a){var b=g.Td("iv-drawer-close-button",a.B);
a.context.g.ca(b,"click",a.VB,a);a.context.g.ca(a.o,"touchend",function(){a.N.start()});
a.context.g.ca(a.o,"scroll",a.eC,a);a.context.i.subscribe("onHideControls",function(){a.T=!0});
a.context.i.subscribe("onShowControls",function(){a.T=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.T=g.po(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.hq("iv-button-shown",a.FD,a));a.I.push(g.hq("iv-button-hidden",a.ED,a));a.I.push(g.hq("iv-teaser-shown",a.ID,a));a.I.push(g.hq("iv-teaser-hidden",a.HD,a));a.I.push(g.hq("iv-teaser-clicked",a.GD,a))},Tna=function(a,b){switch(b.type){case "simple":return o0(a.A,b);
case "collaborator":var c=a.A,d={C:"div",W:["iv-card","iv-card-channel"],J:[{C:"a",W:["iv-click-target"],L:{href:YZ(b.url),"data-ytid":b.channelId},J:[m0(b.profileImageUrl),{C:"div",G:"iv-card-content",J:[r0(c,b),{C:"h2",G:"iv-card-primary-link",U:b.title},p0(c,b)]}]}]};d=new g.S(d);n0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.y)(c.A,c,b),o0(c,b,d,d);case "episode":return q0(a.A,b,"iv-card-episode");case "movie":return q0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={C:"div",W:["iv-card",
"iv-card-playlist"],J:[{C:"a",G:"iv-click-target",L:{href:YZ(b.url)},J:[m0(b.o,{C:"div",G:"iv-card-image-overlay",J:[{C:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{C:"div",G:"iv-card-content",J:[r0(c,b),j0(c,"h2","iv-card-primary-link",b.title),p0(c,b)]}]}]},d=new g.S(d),n0(c,d,b),d;case "poll":return Nna(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=l0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({C:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({C:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={C:"div",J:k});d={C:"div",W:d,L:{tabindex:"0"},J:[{C:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:YZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{C:"div",G:"iv-card-content",J:[b.sponsored?{C:"div",G:"iv-card-sponsored",J:["Sponsored",{C:"div",G:"iv-ad-info-container",J:[{C:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{C:"div",G:"iv-ad-info-icon-container",J:[{C:"div",G:"iv-ad-info-icon"},{C:"div",G:"iv-ad-info-callout"}]}]}]}:"",{C:"a",G:"iv-click-target",L:{href:YZ(b.url)},J:[j0(c,"h2",f,b.title),k]}]}]};d=new g.S(d);f=g.fe("span");g.pe(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(f,"adInfo");n0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.y)(c.D,c,b),o0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{C:"span",W:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={C:"div",W:["iv-card","iv-card-video"],J:[{C:"a",G:"iv-click-target",L:{href:YZ(b.url)},J:[m0(b.o,b.videoDuration?{C:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{C:"div",G:"iv-card-content",J:[r0(c,b),j0(c,"h2","iv-card-primary-link",b.title),p0(c,b),d]}]}]},d=new g.S(d),n0(c,d,b),d}return null},Una=function(a,b){if(0==a.l.length)return 0;
var c=g.fb(a.l,function(a){return b.Db.startMs>a.Db.startMs||b.Db.startMs==a.Db.startMs&&b.Db.timestamp>=a.Db.timestamp?!0:!1});
return-1==c?0:c+1},Yna=function(a){return a.g?"productListing"==a.g.Db.type:(0,g.pj)(a.l,function(a){return"productListing"==a.Db.type})},F0=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",Yna(a))},G0=function(a,b){if(a.F.Ea()){var c=new eZ([0,
a.o.scrollTop],[0,b.Io.offsetTop],600,Jma);a.context.l.ca(c,"animate",function(b){a.o.scrollTop=b.y});
a.context.l.ca(c,"finish",function(b){a.o.scrollTop=b.y});
c.play()}else g.WB(a.F,!0),a.o.scrollTop=b.Io.offsetTop,g.WB(a.F,!1)},H0=function(a){return a.g&&a.g.Db?a.g.Db:a.l[0]&&a.l[0].Db?a.l[0].Db:null},Xna=function(a,b){return g.eb(a.l,function(a){return a.Db.id==b})},I0=function(a,b,c){z0.call(this,a,b);
this.annotation=c;this.isActive=!1},Zna=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},J0=function(a,b,c){I0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.B=this.A=null},K0=function(a,b,c){I0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.B=5E3;this.o=null;this.D=g.ee("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.L(function(){this.g.setAttribute("aria-hidden",!0);g.bi(this.l,!1);g.bi(this.i,!0)},700,this);
g.G(this,this.A)},$na=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.B=b.collapse_delay_ms||a.B;var d=["iv-promo","iv-promo-inactive"];a.ha().setAttribute("aria-hidden",!0);a.ha().setAttribute("aria-label","Promotion");a.ha().tabIndex=0;var e=a.annotation.Eb(),f=b.image_url;if(f){var k=g.ee("DIV",["iv-promo-img","iv-click-target"]);f=g.ee("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.ee("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ee("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.si(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.ee("A","iv-promo-txt"),g.yd(f,YZ(e)),a.g=f):a.g=g.ee("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ee("P",null,g.ee("STRONG",null,b.text_line_1));var m=g.ee("P",null,g.ee("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.sb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ee("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ee("BUTTON",["iv-button","iv-promo-button"],g.ee("SPAN","iv-button-content",f));var q=g.ee("DIV","iv-promo-button-container");q.appendChild(f);e&&a.si(a.ha(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,"iv-click-target");e&&a.si(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.ee("P",null,g.ee("SPAN",null,b.text_line_1)),m=g.ee("P",null,g.ee("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ee("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.si(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);q&&a.D.appendChild(q);c=g.ee("DIV","iv-promo-actions");a.i=g.ee("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.ca(a.i,
"click",g.Wa(a.Fp,5E3),a);c.appendChild(a.i);g.bi(a.i,!1);a.context.g.ca(a.ha(),"mouseover",a.NC,a);a.context.g.ca(a.ha(),"mouseout",a.MC,a);a.context.g.ca(a.ha(),"touchend",g.Wa(a.Fp,5E3),a);a.l=g.ee("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.FC:a.EC,a);c.appendChild(a.l);g.qo(a.ha(),d);k&&(a.ha().appendChild(k),n&&k.appendChild(n));a.ha().appendChild(a.D);a.ha().appendChild(c)},L0=function(a){a.u||a.F||a.o||(g.J(a.ha(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},M0=function(a){a.A.stop();
a.u&&(g.so(a.ha(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.bi(a.i,!1),g.bi(a.l,!0))},O0=function(a,b){a.o||(a.o=g.Pg(function(){N0(this);
L0(this)},b,a))},N0=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},P0=function(a){g.eK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Jna(a);this.A=new g.bs(this);g.G(this,this.A);this.B=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.y)(this.M,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.y)(this.M,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.y)(this.M,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.y)(this.M,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.y)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.eI,this);this.subscribe("onShowControls",this.fK,this);this.subscribe("presentingplayerstatechange",this.oJ,this);this.subscribe("resize",this.zr,this);this.subscribe("G",this.fE,this);this.subscribe("F",this.kg,this);this.subscribe("D",this.cH,this);this.subscribe("E",this.FH,this);g.V(this.player).I.subscribe("vast_info_card_add",this.Iy,this);this.V=new g.bs(this);g.G(this,this.V);this.V.K(this.player,g.DD("annotations_module"),this.dE);this.V.K(this.player,
"crx_annotations_module",this.eE);this.O=g.ee("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.T=g.ee("DIV","video-custom-annotations");this.u=new g.S({C:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.SJ(this.player,this.u.element,4);this.u.hide();this.o=new g.S({C:"div",W:["ytp-iv-video-content"]});g.G(this,this.o);g.he(this.o.element,g.ee("DIV","video-annotations",this.O,this.T));this.F=this.g=null;this.N=[];aoa(this)&&this.load();var b=g.fe("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Af(this,function(){g.ke(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Q0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},aoa=function(a){var b=g.V(a.player);
a=a.player.getVideoData();return 1==(b.Hf||a.Hf)&&!a.BA||null!==b.I.get(a.videoId)},R0=function(a,b,c){a.I=!0;
a.B=g.Pq(b,c)},S0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(S0(a,e))}return c},T0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},coa=function(a,b){var c=boa(a,b);
if(!c&&"marker"!=b.type)return null;p_(b,function(a){a=(0,g.y)(this.DK,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new P_(a.va,b,c);g.G(d,c);return d},doa=function(a,b){var c=g.ee("DIV",["annotation",
"annotation-type-custom"]);g.bi(c,!1);var d=null;switch(b.type){case "branding":if(g.V(a.player).Gc)break;a.u.element.appendChild(c);d=new J0(c,U0(a),b);break;case "promotion":g.SJ(a.player,c,4),d=new K0(c,U0(a),b)}d&&d.Cn();return d},eoa=function(a){var b=a.player.getVideoData();
if(b.Cd){var c=g.V(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Ac:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Ac.gaming="1");e.Xc=(0,g.y)(function(a,b,c){T0(this,a,b)||(a=g.Kq(c)&&c.responseXML?c.responseXML:null)&&V0(this,a)},a,a.H,b.videoId);
g.Ds()&&(e.Xc=W0(a,e.Xc));e.tb={ic_only:"1"};X0(e,d);a.I=!0;g.Pq(b.Cd,e)}}},X0=function(a,b){a.method="POST";
a.tb=a.tb||{};b.ol&&(a.tb.ic_coll=b.ol);b.pl&&(a.tb.ic_xml=b.pl);b.zs&&(a.tb.ic_track=b.zs)},foa=function(a){var b=new g.S({C:"div"});
g.bi(b.element,!1);var c=new C0(a.player,b.element,U0(a));g.G(c,b);b.g(a.u.element);c.Cn();return c},U0=function(a){if(!a.F){var b=new iZ(a);
g.G(a,b);var c=new g.yn(a);g.G(a,c);a.F=new Mna(b,c,g.V(a.player),a.player.getVideoData(),a.D,a.player,a.va)}return a.F},V0=function(a,b){var c=!1;
goa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=S0(a,d[e]),k=null;try{k=una(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=doa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=foa(a),g.G(a,a.g)),"card"==k.type?Vna(a.g,k):Wna(a.g,k),c=!0;else if(f=coa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(VY(a.player),a.zr());g.Zb(a.i,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.i&&
(b=this.i[b.segment.i])&&(a.O=b.annotation)}},a)},goa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.lt();
if(b){var c=g.kt();c&&g.Vs(b,c,[g.Ts(a)])}}},hoa=function(a,b,c,d){d?Y0(a,b,c):Z0(a,b,c)},Z0=function(a,b,c){if(b=a.i[b])R_(b),c&&c.i?(a=(0,g.y)(a.Vv,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Vv(b)},Y0=function(a,b,c){if(b=a.i[b])R_(b),c&&c.o?(a=(0,g.y)(a.Pz,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Pz(b)},$0=function(a,b){var c=a.player.getVideoData();
if(!c.Zk)return!1;var d=YZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!w0(d))return!1;d=g.zq(d);return d.list||d.p?!1:(d=x0(b))?c.videoId==d?!0:"new"!=b.target&&g.V(a.player).i?!0:!1:!1},boa=function(a,b){if(ioa(b)){var c=b.u||n_(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new I_(b,(0,g.y)(a.O.appendChild,a.O),a.player,a.va,c)}return null},ioa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in m_)if(a.style==m_[b])return!0;return!1},a1=function(a,b,c,d){a.M(t_(b,d),c,d)},W0=function(a,b){return(0,g.y)(function(){if(!this.da()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Wa.apply(window,a);this.N.push(g.Bs(b))}},a)};
g.wJ.prototype.pi=g.ca(14,function(a,b){var c=g.xJ(this).l;c&&c.pi(a,b)});
g.Fo.prototype.Cp=g.ca(0,function(){this.i=this.N.createElement("DIV")});
var Cma=/[^\d]+$/,Dma={cm:1,"in":1,mm:1,pc:1,pt:1},Ema={em:1,ex:1},ZY={},$Y=null;g.z(dZ,g.Df);g.z(eZ,g.uo);g.h=eZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;aZ(this);this.startTime=a=(0,g.B)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Pd("play");-1==this.g&&this.Pd("resume");this.g=1;var b=g.Ta(this);b in ZY||(ZY[b]=this);bZ();cZ(this,a);return!0};
g.h.stop=function(a){aZ(this);this.g=0;a&&(this.progress=1);fZ(this,this.progress);this.Pd("stop");this.l()};
g.h.pause=function(){1==this.g&&(aZ(this),this.g=-1,this.Pd("pause"))};
g.h.R=function(){0==this.g||this.stop(!1);this.Pd("destroy");eZ.Ha.R.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.rr=function(){this.Pd("animate")};
g.h.Pd=function(a){this.dispatchEvent(new dZ(a,this))};
g.z(gZ,eZ);gZ.prototype.u=g.Ka;gZ.prototype.rr=function(){this.u();gZ.Ha.rr.call(this)};
gZ.prototype.l=function(){this.u();gZ.Ha.l.call(this)};
gZ.prototype.o=function(){this.u();gZ.Ha.o.call(this)};
g.z(hZ,gZ);hZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.r(iZ,g.E);iZ.prototype.ca=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.Pr(a,b,c);this.g.push(a);return a};
iZ.prototype.km=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.Zr(a,b,c);this.g.push(a);return a};
iZ.prototype.Na=function(a){g.Qr(a);g.nb(this.g,a)};
iZ.prototype.R=function(){g.Qr(this.g);this.g.length=0;g.E.prototype.R.call(this)};g.z(mZ,g.bg);g.h=mZ.prototype;g.h.xp=null;g.h.zj=null;g.h.ha=function(){return this.zj};
g.h.addEventListener=function(a,b,c,d){g.Nf(this.zj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Vf(this.zj,a,b,c,d)};
g.h.R=function(){mZ.Ha.R.call(this);var a=this.zj;if(a)if(g.Gf(a))a.fe&&g.Kf(a.fe);else if(a=g.Qf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Wf(d[e])&&++b}};g.z(rZ,mZ);rZ.prototype.fill=null;g.z(tZ,mZ);uZ.prototype.ye=null;uZ.prototype.ud=null;uZ.prototype.zk=!0;var Mma=[2,2,6,6,0];g.h=uZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ba.length=0;this.Md.length=0;delete this.ye;delete this.ud;delete this.zk;return this};
g.h.moveTo=function(a,b){0==g.ab(this.Ta)?this.Md.length-=2:(this.Ta.push(0),this.Ba.push(1));this.Md.push(a,b);this.ud=this.ye=[a,b];return this};
g.h.Wb=function(a){var b=g.ab(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ba.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Md.push(c,d)}this.Ba[this.Ba.length-1]+=b/2;this.ud=[c,d]};
g.h.close=function(){var a=g.ab(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ba.push(1),this.ud=this.ye);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ba=this.Ba.concat();a.Md=this.Md.concat();a.ye=this.ye&&this.ye.concat();a.ud=this.ud&&this.ud.concat();a.zk=this.zk;return a};
g.h.transform=function(a){if(!this.zk)throw Error("Non-simple path");a.transform(this.Md,0,this.Md,0,this.Md.length/2);this.ye&&a.transform(this.ye,0,this.ye,0,1);this.ud&&this.ye!=this.ud&&a.transform(this.ud,0,this.ud,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.z(wZ,rZ);g.z(yZ,g.Fo);yZ.prototype.o=null;yZ.prototype.pj=function(){return this.Jg?g.ai(this.ha()):g.Ia(this.width)&&g.Ia(this.height)?new g.Jd(this.width,this.height):null};
yZ.prototype.resume=function(){};g.z(oZ,sZ);g.z(nZ,sZ);g.z(zZ,tZ);zZ.prototype.clear=function(){g.ie(this.ha())};
zZ.prototype.setSize=function(a,b){var c=this.ha(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.z(AZ,wZ);var DZ;g.z(BZ,yZ);var Pma=0;g.h=BZ.prototype;g.h.Cp=function(){var a=pZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=pZ(this,"g");this.B=pZ(this,"defs");this.o=new zZ(b,this);a.appendChild(this.B);a.appendChild(b);this.i=a;this.l&&(this.ha().setAttribute("preserveAspectRatio","none"),this.O?this.rA():this.ha().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.rA=function(){if(this.Jg){var a=this.pj();0==a.width?this.ha().style.visibility="hidden":(this.ha().style.visibility="",this.o.ha().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.$h(this.ha(),a,b)};
g.h.pj=function(){if(!g.Kh)return this.Jg?g.ai(this.ha()):BZ.Ha.pj.call(this);var a=this.width,b=this.height,c=g.t(a)&&-1!=a.indexOf("%"),d=g.t(b)&&-1!=b.indexOf("%");if(!this.Jg&&(c||d))return null;if(c){var e=this.ha().parentNode;var f=g.ai(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ha().parentNode,f=f||g.ai(e),b=parseFloat(b)*f.height/100);return new g.Jd(a,b)};
g.h.clear=function(){this.o.clear();g.ie(this.B);this.g={}};
g.h.fj=function(){BZ.Ha.fj.call(this);this.O&&this.P.Na(Qma(),"tick",this.rA)};
g.h.R=function(){delete this.g;delete this.B;delete this.o;this.P.dispose();delete this.P;BZ.Ha.R.call(this)};g.r(FZ,g.eK);g.h=FZ.prototype;
g.h.load=function(){g.eK.prototype.load.call(this);if(!HZ(g.V(this.player).playerStyle)){var a=g.DB(this.player.getVideoData());if(a)a=EZ(a,GZ(this)),IZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.y)(this.VH,this,a),Ac:{v:a},withCredentials:!0};"gaming"==g.V(this.player).playerStyle&&(a.Ac.gaming="1");this.P&&(a.Ac.ptype="embedded");var c=this.player.getVideoData().Ru;c&&(a.tb={ad_tracking:c});if(b=g.CB(b))if(b=g.kd(b),b=g.hd(b))this.o=
g.Pq(b,a)}}};
g.h.unload=function(){IZ(this,null);this.o&&(this.o.abort(),this.o=null);g.eK.prototype.unload.call(this)};
g.h.Vb=function(a,b){if(!HZ(g.V(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=EZ(b,"new");IZ(this,c);return!0}return null};
g.h.getOptions=function(){return HZ(g.V(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.VH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=EZ(c,GZ(this)))}IZ(this,c)};
g.h.qb=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<b1.length;f++){var k=Math.abs(b.width-b1[f]);if(-1==e||d>=k)e=f,d=k}d=c1[e];this.l&&g.Ih(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.$h(e.element,Math.round(k.width*a.width),f);g.Qh(e.element,m,n);g.so(e.element,joa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.so(e.element,c1);g.J(e.element,d);(e=g.Rd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ih(e,"height",f+"px")}}}}};
g.h.hE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.FJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(MZ(this,this.i.impressionUrls),(a=g.lt())&&g.Ws(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");MZ(this,c.impressionUrls);(b=g.lt())&&g.Ws(b,c.visualElement);
g.V(this.player).ub&&this.player.la("endscreenelementshown",a)}};
g.h.iE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.ro(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.ro(b,"ytp-ce-shown");g.V(this.player).ub&&this.player.la("endscreenelementhidden",a)}};
g.h.SK=function(a){var b=this;a.target===window&&(new g.L(function(){for(var a in b.g)g.so(b.g[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.hy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.po(c,"ytp-ce-element");){g.po(c,"subscribe-label")&&NZ(this,a);if(g.po(c,"ytp-ce-channel-subscribe"))return;c=g.ne(c)}if(!c||g.po(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.yr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.In?(NZ(this,a),this.xz(),this.player.pauseVideo(),c=g.kd(a.targetUrl),c=g.hd(c),g.SL(c,void 0,a.Yc)):(c=this.player.getVideoData().Xb,
c=(0,g.y)(this.GL,this,c,a.targetUrl,a.Yc),c=(0,g.y)(this.xz,this,c),NZ(this,a,c))}}};
g.h.GL=function(a,b,c){var d=g.zq(b);a&&d&&(d.v||d.list)?g.tX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.RL(b,c)};
g.h.Dq=function(a,b){g.po(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.V(this.player).g?(new g.L(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),MZ(this,b.jD),LZ(this,b.id,!0))};
g.h.yr=function(a,b){g.ro(a.element,"ytp-ce-element-hover");g.ro(a.element,"ytp-ce-force-expand");LZ(this,b.id,!1)};
g.h.xz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var b1=[346,426,470,506,570,640,853,1280,1920],c1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),joa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ana={fN:"current",mO:"new"};var cna={CLOSE:"close",pO:"openUrl",zB:"subscribe"},dna={aN:"click",CLOSE:"close",HN:"hidden",OO:"rollOut",sB:"rollOver",uB:"shown"};var fna={sP:"xx",tP:"xy",uP:"yx",vP:"yy"};g.r(h_,a_);var kna={OA:"anchored",KO:"rect",RO:"shapeless"};var ona={CLOSED:"closed",yO:"playerControlShow",sB:"rollOver",uB:"shown"};l_.prototype.Eb=function(){var a=wna(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
l_.prototype.showLinkIcon=function(){return n_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var m_={OA:"anchored",RA:"branding",CHANNEL:"channel",eN:"cta",JN:"highlightText",XN:"label",PLAYLIST:"playlist",BO:"popup",VO:"speech",zB:"subscribe",eP:"title",VIDEO:"video",oP:"website"},sna={RA:"branding",RM:"card",lN:"drawer",IN:"highlight",fO:"marker",GO:"promotion",TEXT:"text",qP:"widget"},tna={mP:"video_relative",zO:"player_relative"};u_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.cc(this.g,function(a){return a});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};v_.prototype.ha=function(){return this.u};
v_.prototype.l=function(){};var z_={bevel:1,dropshadow:2};g.r(E_,v_);
E_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=q_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.yh(c_(b,d_(e,new g.vh(e.D,e.F,e.Fi,e.l),b.g))),k=d.clone();c=new g.vh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=C_(k,c.effects);l=w_(this,k.width,k.height);m=B_(c,k.width,k.height,this.g);
d=new g.vh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Hd(f.x-k.left,f.y-k.top);this.o=17*$Z(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var q=this.g&&o_(a),u=q?f.borderWidth+1:f.borderWidth;q=(f=u?new xZ(u,q?f.i:f.borderColor):null)?f.g/2:0;u=Ena(d,n);var x=this.A(d,e,n,u),C=n.x;n=n.y;var F=d.width,H=d.height,T=d.left;d=d.top;var X=new uZ;X.moveTo(T+e+q,d+q);"t"==u&&(X.Wb(x.start,d+q),X.Wb(C,n),X.Wb(x.end,d+q));X.Wb(T+F-e-q,d+q);vZ(X,e,e,-90);"r"==u&&(X.Wb(T+F-q,x.start),X.Wb(C,n),X.Wb(T+
F-q,x.end));X.Wb(T+F-q,d+H-e-q);vZ(X,e,e,0);"b"==u&&(X.Wb(x.end,d+H-q),X.Wb(C,n),X.Wb(x.start,d+H-q));X.Wb(T+e+q,d+H-q);vZ(X,e,e,90);"l"==u&&(X.Wb(T+q,x.end),X.Wb(C,n),X.Wb(T+q,x.start));X.Wb(T+q,d+e+q);vZ(X,e,e,180);X.close();CZ(l,X,f,m);if(m=this.ha())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Qh(m,k.left,k.top),g.$h(m,k.width,k.height),D_(l,m,c.effects)}}}};
E_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Cd(c-a/2,d+b,d+e-a-b);return new g.Zi(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Zi(0,0)};g.r(F_,v_);F_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=C_(d,e.effects);var f=w_(this,c.width,c.height),k=new xZ(!e.l&&this.g?1:e.l,e.bgColor),l=new nZ("#000",0);d=A_(new g.vh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);CZ(f,d,k,l);f=this.ha();g.J(f,"annotation-shape");e=e.g;XY(f,this.g?Math.max(e,.9):e);g.Qh(f,c.left,c.top);g.$h(f,c.width,c.height)}}};g.r(G_,v_);
G_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=C_(d,c.effects),f=w_(this,e.width,e.height),k=new g.vh(0,0,d.width,d.height);d=B_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&o_(a),q=n?m.borderWidth+1:m.borderWidth;m=q?new xZ(q,n?m.i:m.borderColor):null;k=A_(k,l,m?m.g/2+1:0);CZ(f,k,m,d);if(k=this.ha())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Qh(k,e.left,e.top),g.$h(k,e.width,e.height),D_(f,k,c.effects)}}};g.r(H_,E_);H_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new g.Zi(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Zi(0,0)};g.r(I_,g.E);g.h=I_.prototype;g.h.Tw=function(){this.F||(this.o&&g.bi(this.o,!0),this.u&&g.bi(this.u,!0),this.l&&(this.l.g=!0,XY(this.i,N_(this)?1:0),this.l.l(this.g,K_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ba.km(g.CJ(this.A),"mouseleave",function(a){this.Nm.stop();this.kg(a)}))};
g.h.kg=function(){this.F&&(this.N?this.D.start():this.Wv(),this.l&&(this.l.g=!1,XY(this.i,N_(this)?1:0),this.l.l(this.g,K_(this))),this.F=!1,this.H&&(this.ba.Na(this.H),this.H=null))};
g.h.Wv=function(){this.o&&g.bi(this.o,!1);this.u&&g.bi(this.u,!1)};
g.h.VE=function(a){this.aa=a;this.Nm.xj()};
g.h.LC=function(){var a=this.aa,b=new g.Hd(a.clientX,a.clientY),c=g.Uh(this.A.getRootNode()),d=O_(c,this.P);c=(this.u&&YY(this.u)||this.o&&YY(this.o))&&O_(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.Tw(a):this.kg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=K_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new F_:"popup"==this.g.style?d=new G_:"anchored"==this.g.style?d=new E_:"speech"==this.g.style&&(d=new H_);d&&(d.l(this.g,c),this.l=d,c=d.ha())&&(g.bi(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.V(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.ee("DIV",c);g.bi(this.i,!1);this.g.o&&(this.B=g.ee("DIV","inner-text"),"label"==this.g.style&&(g.J(this.B,"player-label-text"),this.B.style.backgroundColor=this.g.i.bgColor),g.pe(this.B,this.g.o),this.i.appendChild(this.B));g.Yp(this.i,"annotation_id",this.g.id);this.V(this.i);Fna(this,this.i);if(o_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Eb())c=this.i,d=new g.jn(YZ(d)),c.title=d.g+d.i;this.u=g.ee("SPAN","annotation-link-icon");g.bi(this.u,
!1);this.i.appendChild(this.u)}Gna(this);o_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=j_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ha()&&(this.l.ha().style.zIndex=a)}g.bi(this.i,!0);XY(this.i,N_(this)?1:0);M_(this);this.l&&this.l.ha()&&g.bi(this.l.ha(),!0)};
g.h.hide=function(){this.i&&g.bi(this.i,!1);this.l&&this.l.ha()&&g.bi(this.l.ha(),!1);this.I&&(this.ba.Na(this.I),this.I=null)};g.r(P_,g.E);g.h=P_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(Q_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.Sw,this),this.i.subscribe("onVideoAreaChange",this.Jy,this))};
g.h.destroy=function(){if(this.view){Q_(this);var a=this.view,b=a.ba;g.Qr(b.g);b.g.length=0;a.Nm.dispose();a.D.dispose();a.i&&g.ke(a.i);a.l&&a.l.ha()&&g.ke(a.l.ha())}R_(this)};
g.h.Jy=function(){M_(this.view)};
g.h.Sw=function(){M_(this.view)};g.r(S_,lZ);g.r(T_,lZ);g.r(U_,T_);g.r(V_,lZ);g.r(W_,lZ);g.r(X_,T_);g.r(Y_,T_);g.r(Z_,lZ);g.r($_,lZ);i0.prototype.l=function(a,b){var c=g.ue(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
i0.prototype.B=function(a,b){var c=g.ue(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Td("iv-card-sign-in-button",c).click();else{var d=parseInt(Gma(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;k0(a,c);g.Tq(this.g.videoData.Cd,{Ac:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.F}});e0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.lt())&&g.Xs(c,a.A)}};
i0.prototype.A=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.B)});
s0(this,a,!0,c)};
i0.prototype.D=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Wa(b,a.P,a.F,a.B));s0(this,a,!1,b)};g.r(z0,g.E);g.h=z0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.AD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&UY(a).subscribe("onEnter",d,this);e&&UY(a).subscribe("onExit",e,this);g.LJ(this.context.ea,[a])};
g.h.Cn=function(){this.context.i.subscribe("resize",this.il,this)};
g.h.ha=function(){return this.za};
g.h.si=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Wa(this.jm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Wa(function(){this.Ls=!1}),this);
this.context.g.ca(a,"touchmove",g.Wa(function(){this.Ls=!0}),this)};
g.h.jm=function(a,b,c,d,e,f,k){if(this.Ls)return!1;k&&(k.stopPropagation(),k.preventDefault());Rna(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.B)()};
g.h.hide=function(){};
g.h.destroy=function(){g.ke(this.ha())};
g.h.il=function(){};g.r(C0,z0);g.h=C0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.ai(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.il=function(){var a=this.isAvailable();g.bi(this.ha(),a);g.K(this.context.ea.getRootNode(),"ytp-iv-drawer-enabled",a);VY(this.i)};
g.h.destroy=function(){this.i.pi(!1);this.i.getRootNode().removeChild(this.B);g.iq(this.I);g.Qr(this.aa);this.Y&&this.Y.dispose();this.D&&this.D.dispose();z0.prototype.destroy.call(this)};
g.h.xE=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Dz=function(a){if(!g.po(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.lt(),c=this.g?this.g.Db.u:this.H;b&&c&&kZ(b,[c]);this.g=a;F0(this)}YY(this.ha())&&(2==this.context.ea.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.ea.getAdState():void 0):(b=isNaN(void 0)?this.context.ea.getPlayerState():void 0,b=1==b||0==b&&0===this.context.ea.getCurrentTime()),b&&a.Db.teaserDurationMs&&this.i.pi(!0,{teaserText:a.Db.teaserText,durationMs:a.Db.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.N.isActive()&&this.T)&&G0(this,a),this.ka.start(910+a.Db.teaserDurationMs))}};
g.h.AL=function(a){this.u||(this.g=a,F0(this),G0(this,a),A0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.VB=function(){if(this.u){g0(this.context.logger,this.V,4,H0(this).i.close);var a=g.lt();a&&this.P&&g.Xs(a,this.P);B0(this)}};
g.h.eC=function(){g.K(this.B,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.FD=function(){var a=g.lt(),b=H0(this);b=b?b.u:this.H;a&&b&&jZ(a,[b])};
g.h.ED=function(){var a=g.lt(),b=H0(this);b=b?b.u:this.H;a&&b&&kZ(a,[b])};
g.h.ID=function(){var a=H0(this);h0(this.context.logger,8,a.l,a.i.LL);var b=g.lt();b&&a&&jZ(b,[a.D,a.u])};
g.h.HD=function(){var a=g.lt(),b=H0(this);a&&b&&kZ(a,[b.D])};
g.h.GD=function(a){var b=H0(this),c=g.lt();this.g?a?(a=this.context.logger,h0(a,9,b.l,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Xs(c,b.D)):(a=this.context.logger,h0(a,12,b.l,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Xs(c,b.u)):(a=this.context.logger,g0(a,this.V,12,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Xs(c,this.H))};
var D0={collaborator:S_,donation:U_,episode:$_,movie:$_,playlist:V_,poll:W_,productListing:X_,simple:T_,tip:Y_,video:Z_};g.r(I0,z0);I0.prototype.Cn=function(){z0.prototype.Cn.call(this);Zna(this)};
I0.prototype.show=function(){z0.prototype.show.call(this);var a=g.lt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&jZ(a,[g.Ts(b.itct)])};
I0.prototype.hide=function(){z0.prototype.hide.call(this);var a=g.lt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&kZ(a,[g.Ts(b.itct)])};g.r(J0,I0);g.h=J0.prototype;g.h.HL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.ai(a);this.g||(g.Zh(a,e.width),g.Zh(b,e.width));g.Ih(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Ih(c,"right","1px");this.o=!0;g.bi(a,!0);this.A=new g.L(function(){g.J(this.ha(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.iD=function(a,b){g.ro(this.ha(),"iv-branding-active");this.B=new g.L((0,g.y)(function(){g.bi(a,!1);this.g||g.Zh(b,0)},this),250);
this.B.start();this.o=!1};
g.h.show=function(){if(!this.isActive){I0.prototype.show.call(this);if(!this.D){g.J(this.ha(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.ee("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.bi(this.i,!1);var b=g.ee("DIV","branding-img-container",this.i);this.ha().appendChild(b);var c=g.ee("DIV","iv-branding-context-name");g.pe(c,a.channel_name);var d=g.ee("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.jV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ea),this.g.g(d);b=g.ee("DIV","iv-branding-context-subscribe-caret");c=g.ee("DIV","branding-context-container-inner",b,c,d);g.bi(c,!1);d=g.ee("DIV","branding-context-container-outer",c);g.Ih(d,"right",this.u+"px");this.ha().appendChild(d);var e=this.annotation.Eb();e&&this.si(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.L(g.Wa(this.iD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ha(),"mouseover",(0,g.y)(this.HL,this,c,d,b,a.image_height));this.context.g.ca(this.ha(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}d0(this.context.logger,this.annotation.g);g.bi(this.ha(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=WY(a).width;c=g.Ia(void 0)?void 0:b;g.Qh(a,c);f=new hZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Ima);g.G(this,f);this.context.l.ca(f,
"begin",g.Wa(g.bi,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(I0.prototype.hide.call(this),g.bi(this.ha(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);I0.prototype.destroy.call(this)};g.r(K0,I0);g.h=K0.prototype;g.h.show=function(){this.isActive||(I0.prototype.show.call(this),this.H||($na(this),this.H=!0),g.bi(this.ha(),!0),this.annotation&&this.annotation.g&&d0(this.context.logger,this.annotation.g),g.Pg(function(){g.ro(this.ha(),"iv-promo-inactive")},100,this),this.ha().removeAttribute("aria-hidden"),this.isActive=!0,N0(this),M0(this),O0(this,this.B))};
g.h.hide=function(){this.isActive&&(g.J(this.ha(),"iv-promo-inactive"),this.isActive=!1,this.ha().setAttribute("aria-hidden",!0))};
g.h.jm=function(a,b,c,d,e,f,k){return this.u?!1:I0.prototype.jm.call(this,a,b,c,d,e,f,k)};
g.h.Fp=function(a,b){b.stopPropagation();M0(this);O0(this,a);this.g.focus()};
g.h.NC=function(a){this.F=!0;this.Fp(500,a)};
g.h.MC=function(){this.F=!1;L0(this)};
g.h.EC=function(a){a.stopPropagation();this.hide();f0(this.context.logger,this.annotation.g)};
g.h.FC=function(a){a.stopPropagation();N0(this);this.u=!0;g.J(this.ha(),"iv-promo-collapsed-no-delay");this.A.start();f0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();I0.prototype.destroy.call(this)};g.r(P0,g.eK);g.h=P0.prototype;g.h.Vb=function(a,b){if(!Q0(g.V(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.to(b);c&&V0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(E0(this.g,b),VY(this.player)),!0}return null};
g.h.getOptions=function(){return Q0(g.V(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.zr=function(){if(this.o){var a=g.CJ(this.player).getVideoContentRect(!0);g.$h(this.o.element,a.width,a.height);g.Qh(this.o.element,a.left,a.top)}if(this.g){var b=g.JJ(this.player);a=this.g;b=b.width;g.K(a.B,"iv-drawer-small",426>=b);g.K(a.B,"iv-drawer-big",1280<=b)}};
g.h.oJ=function(a){this.ec(a.state);g.U(a.state,2)&&(this.sd()&&this.ue()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.pi(!1))};
g.h.load=function(){g.eK.prototype.load.call(this);this.ec(g.BJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.WH,this,b,this.H),d=(0,g.y)(function(){this.B=null},this);
g.Ds()&&(c=W0(this,c));c={format:"XML",Xc:c,onError:d,Ac:{}};a.isPharma&&(c.Ac.pharma="1");c.method="POST";c.withCredentials=!0;d=g.V(this.player);"gaming"==d.playerStyle&&(c.Ac.gaming="1");(b=d.I.get(b))&&X0(c,b);b=b&&(b.pl||b.ol);if(!a.Yk||b)a.Cd?R0(this,a.Cd,c):(this.l=(0,g.y)(this.gE,this,c),this.player.addEventListener("videodatachange",this.l));g.SJ(this.player,this.o.element,4);this.zr()};
g.h.ec=function(a){a=!a.isCued()&&!g.U(a,1024);g.WB(this.u,a);g.WB(this.o,a)};
g.h.gE=function(a){var b=this.player.getVideoData();b.Cd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),R0(this,b.Cd,a))};
g.h.unload=function(){Kna(this.D);g.OJ(this.player,"annotations_module");g.Zb(this.i,function(a){a.destroy()});
g.Zb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,VY(this.player));this.I=!1;this.B&&(this.B.abort(),this.B=null);this.i={};this.P={};this.u.hide();g.eK.prototype.unload.call(this);g.VB(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.WH=function(a,b,c){this.B=null;if(!T0(this,b,a)&&(a=g.Kq(c)&&c.responseXML?c.responseXML:null)){V0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.AD(c,e,f);a.push(b)}}g.LJ(this.player,a)}};
g.h.Iy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?eoa(this):this.load())};
g.h.dE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,Y0(this,a),d0(this.D,b.g))};
g.h.eE=function(a){Z0(this,a.getId())};
g.h.Vv=function(a){a&&(a.hide(),a1(this,"shown",!1,a.annotation.id),this.xl(a.annotation,"hidden"))};
g.h.Pz=function(a){a&&(a.show(),a1(this,"shown",!0,a.annotation.id),this.xl(a.annotation,"shown"))};
g.h.DK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;p_(d.annotation,function(a){e=e||a.value});
hoa(this,a,b,e)}};
g.h.cH=function(a){if(a&&a.id){var b=a.Eb();if(b){var c=YZ(b);if(c){var d=(0,g.y)(this.xl,this,a,"click");if("new"==y0(c,b.target)||$0(this,b))d(),d=null;e0(this.D,a.g,d)}}}};
g.h.xl=function(a,b){vna(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!$0(this,c.url))){e=x0(c.url);var f=Ona(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=U0(this).ea,g.tX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&U0(this).ea.Zb()&&U0(this).ea.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.V(this.player),(d=YZ(c.url))?(f=v0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Wa(Pna,e.pageId,e.qc),d=new g.jn(d),e=e(d.i),d.i=e,d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=y0(d,c.url.target),e=a.itct,"ei"in g.zq(d)&&(d=g.ph(d,"ei")),g.SL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.eI=function(){a1(this,"playerControlShow",!1)};
g.h.fK=function(){a1(this,"playerControlShow",!0)};
g.h.fE=function(a){a1(this,"rollOver",!0,a.id)};
g.h.kg=function(a){a1(this,"rollOver",!1,a.id)};
g.h.FH=function(a){a&&a.id&&(this.i[a.id].l=!0,Z0(this,a.id),f0(this.D,a.g),this.xl(a,"close"),a1(this,"closed",!0,a.id))};
g.h.sd=function(){return!!this.g&&this.g.isAvailable()};
g.h.ue=function(){this.sd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.sd();this.g&&(a?c?A0(this.g,c,b):A0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):B0(this.g))};
g.h.pi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.R=function(){g.V(this.player).I.unsubscribe("vast_info_card_add",this.Iy,this);g.ro(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.N,b=0,c=a.length;b<c;b++)g.Es(a[b]);this.N.length=0;g.eK.prototype.R.call(this)};g.rU.annotations_module=P0;g.rU.creatorendscreen=FZ;})(_yt_player);
